/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.CursoDAO;

/**
 *
 * @author kashiki
 */
public class Alunos extends javax.swing.JPanel {

    /**
     * Creates new form Alunos
     */
    public Alunos() {
        initComponents();
        CursoDAO.showCursosComboBox(cmbCurso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbDataNascimento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbClasse = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBI = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNome.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bg.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("E-mail:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        txtEmail.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bg.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 250, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("Genero:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 137, -1, -1));

        cmbGenero.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        bg.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 164, 250, 39));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("Data de nascimento:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        cmbDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy / MM / dd"))));
        bg.add(cmbDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 250, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Curso:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 221, -1, -1));

        bg.add(cmbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 242, 250, 36));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("Classe:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        bg.add(cmbClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, 36));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setText("Telefone:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        bg.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 250, 36));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("B.I");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));
        bg.add(txtBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 250, 30));

        btnCadastrar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cadastrar");

        javax.swing.GroupLayout btnCadastrarLayout = new javax.swing.GroupLayout(btnCadastrar);
        btnCadastrar.setLayout(btnCadastrarLayout);
        btnCadastrarLayout.setHorizontalGroup(
            btnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCadastrarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(23, 23, 23))
        );
        btnCadastrarLayout.setVerticalGroup(
            btnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCadastrarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        bg.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCadastrar;
    private javax.swing.JComboBox<String> cmbClasse;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JFormattedTextField cmbDataNascimento;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
