package forms;

import beans.Curso;
import dao.CursoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Cursos extends javax.swing.JPanel {

    public Cursos() {
        initComponents();
        showCursosTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Curso:");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 30));

        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });
        bg.add(txtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel4.setText("Gerenciador de Cursos");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        tbCursos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cursos"
            }
        ));
        jScrollPane2.setViewportView(tbCursos);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 460, 180));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        bg.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String nomeCurso = this.txtCurso.getText();
        
        if(nomeCurso.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um curso");
        } else {
            Curso curso = new Curso();
            CursoDAO cursoDAO = new CursoDAO();
            
            curso.setCurso(nomeCurso);
            if(cursoDAO.createdCurso(curso) == false) {
                JOptionPane.showMessageDialog(this, "Curso ja cadastrado");
            }else showCursosTable();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        btnAddActionPerformed(evt);
    }//GEN-LAST:event_txtCursoActionPerformed

    private void showCursosTable() {
        CursoDAO cursoDAO = new CursoDAO();
        List<Curso> listCursos = cursoDAO.getCursos();
        DefaultTableModel tabelaCursos = (DefaultTableModel) this.tbCursos.getModel();
        
        tabelaCursos.setNumRows(0);
        listCursos.forEach((curso) -> {
            Object[] obj = new Object[] {
                curso.getCurso()
            };
            tabelaCursos.addRow(obj);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCursos;
    private javax.swing.JTextField txtCurso;
    // End of variables declaration//GEN-END:variables
}
