/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import sistemapropina.Global;

/**
 *
 * @author kashiki
 */
public class MainPainel extends javax.swing.JFrame {

    /**
     * Creates new form MainPainel
     */
    public MainPainel() {
        initComponents();
        Global.showContent(articleContent, new Welcome());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        navMenu = new javax.swing.JPanel();
        btnAlunos = new javax.swing.JPanel();
        txtAluno = new javax.swing.JLabel();
        btnCursos = new javax.swing.JPanel();
        txtCursos = new javax.swing.JLabel();
        btnPagamento = new javax.swing.JPanel();
        textPagamento = new javax.swing.JLabel();
        iconPagamento = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JPanel();
        iconConsulta = new javax.swing.JLabel();
        textConsulta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMenuHide = new javax.swing.JPanel();
        iconMenuHide = new javax.swing.JLabel();
        articleContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navMenu.setBackground(new java.awt.Color(0, 18, 51));

        btnAlunos.setBackground(new java.awt.Color(0, 24, 63));
        btnAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlunosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
        });

        txtAluno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtAluno.setForeground(new java.awt.Color(255, 255, 255));
        txtAluno.setText("Alunos");

        javax.swing.GroupLayout btnAlunosLayout = new javax.swing.GroupLayout(btnAlunos);
        btnAlunos.setLayout(btnAlunosLayout);
        btnAlunosLayout.setHorizontalGroup(
            btnAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAlunosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAluno)
                .addGap(48, 48, 48))
        );
        btnAlunosLayout.setVerticalGroup(
            btnAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlunosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtAluno)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnCursos.setBackground(new java.awt.Color(0, 24, 63));
        btnCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCursosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
        });

        txtCursos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCursos.setForeground(new java.awt.Color(255, 255, 255));
        txtCursos.setText("Cursos");

        javax.swing.GroupLayout btnCursosLayout = new javax.swing.GroupLayout(btnCursos);
        btnCursos.setLayout(btnCursosLayout);
        btnCursosLayout.setHorizontalGroup(
            btnCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCursosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCursos)
                .addGap(50, 50, 50))
        );
        btnCursosLayout.setVerticalGroup(
            btnCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCursosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtCursos)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnPagamento.setBackground(new java.awt.Color(0, 24, 63));
        btnPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagamentoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
        });

        textPagamento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textPagamento.setForeground(new java.awt.Color(255, 255, 255));
        textPagamento.setText("Pagamentos");

        iconPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money-check-alt.redimensionado.png"))); // NOI18N

        javax.swing.GroupLayout btnPagamentoLayout = new javax.swing.GroupLayout(btnPagamento);
        btnPagamento.setLayout(btnPagamentoLayout);
        btnPagamentoLayout.setHorizontalGroup(
            btnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPagamentoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPagamento)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btnPagamentoLayout.setVerticalGroup(
            btnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPagamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPagamentoLayout.createSequentialGroup()
                        .addComponent(textPagamento)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );

        btnConsulta.setBackground(new java.awt.Color(0, 24, 63));
        btnConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItensHover(evt);
            }
        });

        iconConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.redimensionado.png"))); // NOI18N

        textConsulta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textConsulta.setForeground(new java.awt.Color(255, 255, 255));
        textConsulta.setText("Consultas");

        javax.swing.GroupLayout btnConsultaLayout = new javax.swing.GroupLayout(btnConsulta);
        btnConsulta.setLayout(btnConsultaLayout);
        btnConsultaLayout.setHorizontalGroup(
            btnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textConsulta)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btnConsultaLayout.setVerticalGroup(
            btnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconConsulta)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultaLayout.createSequentialGroup()
                        .addComponent(textConsulta)
                        .addGap(13, 13, 13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 18, 51));

        jLabel1.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SGP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMenuHide.setBackground(new java.awt.Color(0, 18, 51));
        btnMenuHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuHideMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuHover(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuHover(evt);
            }
        });

        iconMenuHide.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        iconMenuHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu_32px.png"))); // NOI18N
        iconMenuHide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnMenuHideLayout = new javax.swing.GroupLayout(btnMenuHide);
        btnMenuHide.setLayout(btnMenuHideLayout);
        btnMenuHideLayout.setHorizontalGroup(
            btnMenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuHideLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iconMenuHide)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnMenuHideLayout.setVerticalGroup(
            btnMenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuHideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconMenuHide)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navMenuLayout = new javax.swing.GroupLayout(navMenu);
        navMenu.setLayout(navMenuLayout);
        navMenuLayout.setHorizontalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(navMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnMenuHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navMenuLayout.setVerticalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnMenuHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        bg.add(navMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        articleContent.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout articleContentLayout = new javax.swing.GroupLayout(articleContent);
        articleContent.setLayout(articleContentLayout);
        articleContentLayout.setHorizontalGroup(
            articleContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        articleContentLayout.setVerticalGroup(
            articleContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        bg.add(articleContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 730, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* */
    
    
    
    /* */
    
    private void btnPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagamentoMouseClicked
        Global.showContent(articleContent, new Pagamento());
    }//GEN-LAST:event_btnPagamentoMouseClicked

    private void btnConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseClicked
        Global.showContent(articleContent, new Consulta());
    }//GEN-LAST:event_btnConsultaMouseClicked

    private void menuItensHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItensHover
        String type = evt.paramString();
        Component comp = evt.getComponent();
        
        if(type.indexOf("MOUSE_ENTERED") != -1) {
            comp.setBackground(Color.getColor("#1B3561"));
        }
        
        if(type.indexOf("MOUSE_EXITED") != -1) {
            comp.setBackground(new Color(0, 24, 63));
        }
    }//GEN-LAST:event_menuItensHover

    private void btnAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlunosMouseClicked
        Global.showContent(articleContent, new Alunos());
    }//GEN-LAST:event_btnAlunosMouseClicked

    private void btnCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMouseClicked
        Global.showContent(articleContent, new Cursos());
    }//GEN-LAST:event_btnCursosMouseClicked

    private void btnMenuHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuHover
        // TODO add your handling code here:
        String type = evt.paramString();
        Component element = evt.getComponent();
        
        if(type.indexOf("MOUSE_ENTERED") != -1) {
            element.setBackground(Color.getColor("00183F"));
        }
        if(type.indexOf("MOUSE_EXITED") != -1) {
            element.setBackground(Color.getColor("001233"));
        }
        
    }//GEN-LAST:event_btnMenuHover

    private void btnMenuHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuHideMouseClicked
        // TODO add your handling code here:
        int widthNavMenu = 0, widthContent = 0, prefixoNavMenuInicial = 70, prefixoNavMenuFinal = 160;
        if (this.navMenu.getWidth() == prefixoNavMenuFinal) {
            widthNavMenu = prefixoNavMenuInicial;
            widthContent = this.articleContent.getWidth() + prefixoNavMenuFinal;
            
        }
        else {
            widthNavMenu = prefixoNavMenuFinal;
            widthContent = this.articleContent.getWidth() - prefixoNavMenuInicial;
        }
        this.navMenu.setSize(widthNavMenu, this.navMenu.getHeight());
        this.articleContent.setLocation(widthNavMenu, 0);
        this.articleContent.setSize(widthContent, this.articleContent.getHeight());
    }//GEN-LAST:event_btnMenuHideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel articleContent;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnAlunos;
    private javax.swing.JPanel btnConsulta;
    private javax.swing.JPanel btnCursos;
    private javax.swing.JPanel btnMenuHide;
    private javax.swing.JPanel btnPagamento;
    private javax.swing.JLabel iconConsulta;
    private javax.swing.JLabel iconMenuHide;
    private javax.swing.JLabel iconPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel navMenu;
    private javax.swing.JLabel textConsulta;
    private javax.swing.JLabel textPagamento;
    private javax.swing.JLabel txtAluno;
    private javax.swing.JLabel txtCursos;
    // End of variables declaration//GEN-END:variables
}
